// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oefening.Data;

namespace Oefening.Migrations
{
    [DbContext(typeof(HelloCoreContext))]
    [Migration("20190403113642_Migration2")]
    partial class Migration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Oefening.Models.Bestelling", b =>
                {
                    b.Property<int>("BestellingID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Artikel");

                    b.Property<int>("KlantID");

                    b.Property<decimal?>("Prijs")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BestellingID");

                    b.HasIndex("KlantID");

                    b.ToTable("Bestelling");
                });

            modelBuilder.Entity("Oefening.Models.Klant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AangemaaktDatum");

                    b.Property<string>("Naam")
                        .IsRequired();

                    b.Property<string>("Voornaam");

                    b.HasKey("ID");

                    b.ToTable("Klant");
                });

            modelBuilder.Entity("Oefening.Models.Bestelling", b =>
                {
                    b.HasOne("Oefening.Models.Klant", "Klant")
                        .WithMany("Bestellingen")
                        .HasForeignKey("KlantID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
